# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://yuv4r4j.github.io/esplike/"

git_url = "https://github.com/yuv4r4j/esplike/tree/master/"

def custom_doc_links(name): return None
